apiVersion: v1
kind: Service
metadata:
  name: inspectron-api
  labels:
    app.kubernetes.io/name: inspectron
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app: inspectron-api
  ports:
    - port: 80
      targetPort: 80
      name: http
